# pylint: skip-file
# Generated by Django 4.2.6 on 2023-11-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_websiteuser_leluuser_uuid_websiteusertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuser',
            name='name',
        ),
    ]
