# pylint: skip-file
# Generated by Django 4.2.6 on 2023-12-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_websiteuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='name',
            field=models.CharField(default='user', max_length=200),
            preserve_default=False,
        ),
    ]
