networks:
    auth:
      name: auth
services:
  auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: leluchat_auth
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - auth
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './redisdata:/data'
    networks:
      - auth
  celery:
    build: .
    command: celery -A leluchat_auth worker -l INFO
    volumes:
      - .:/code
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - auth
    depends_on:
      - auth
      - redis
