networks:
    auth:
      name: auth
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './redisdata:/data'
    networks:
      - auth
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - auth
  auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: leluchat_auth
    environment:
      - DJANGO_RPC_SERVERS_START=TRUE
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - auth
    depends_on:
      - rabbitmq
