networks:
    leluchat:
      name: leluchat
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - './redisdata:/data'
    networks:
      - leluchat
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - leluchat
  auth:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: leluchat_auth
    environment:
      - DJANGO_RPC_SERVERS_START=TRUE
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - leluchat
    depends_on:
      - rabbitmq
  celery:
    build: .
    command: celery -A leluchat_auth worker -l INFO
    volumes:
      - .:/code
    environment:
      - DJANGO_RPC_SERVERS_START=FALSE
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - leluchat
    depends_on:
      - auth
      - redis
