name: release

on: [push]

jobs:
  lint:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  dev-docker-release:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: freeuphub/leluchat_auth:latest
    needs: lint

  dev-docker-test:
    if: ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    container:
      image: freeuphub/leluchat_auth:latest
    steps:
      - name: Run django test
        run: python /code/manage.py test
    needs: dev-docker-release

  prod-docker-release:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: freeuphub/leluchat_auth:${{ github.ref_name }}
